name: easylive_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  intl: ^0.18.1
  image_picker: ^1.1.2
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700

  assets:
    - assets/images/logo-easylive.png
    - assets/images/easylive-baru.png
    - assets/images/kos1.jpg
    - assets/images/kos2.jpg
    - assets/images/kos3.jpg
    - assets/images/login-bg.png
    - assets/images/register.png
    - assets/images/mobilBox-BackgroundRemover.jpg
    - assets/images/pickup-removed.png
    - assets/images/kamarKos.jpg
    - assets/images/qris.jpeg
